AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: IAmNater Auth API
  
Globals:
  Function:
    Timeout: 3

Resources:
  IAmNaterGraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Environment:
        Variables:
          NODE_ENV: development
          SERVER_PORT: 3000
          CLIENT_ID: clientid
          CLIENT_SECRET: clientsecret
      Events:
        GraphQlRequest:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: POST

